create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.waitlist_signups enable row level security;
alter table public.waitlist_signups force row level security;

grant usage on schema public to anon;
grant insert on table public.waitlist_signups to anon;

drop policy if exists "Allow anon inserts to waitlist" on public.waitlist_signups;

create policy "Allow anon inserts to waitlist"
on public.waitlist_signups
for insert
to anon
with check (true);
